### ISSUE TITLE
consider adding mine?

### ISSUE THREAD

**Issue by vackyton** [obscurerev/FNF-Mods-in-Full-Screen#1]
I made my own fnf site since snipergaming888.gtihub.io got blocked so i made https://vackyton.github.io/FNFBiggerModAttempt/

I added nuclear whitty (maybe new song for it) i am just asking if you could add it here

**Comment by obscurerev** [comment]
I don't know since all of these aren't ported by me. I just extract the raw full screen links and put them on here.

**Comment by obscurerev** [comment]
if you have a link for it in full screen, I could possibly add it.

**Comment by vackyton** [comment]
it is full screen
